### PR TITLE
Add GitHub Actions CI suite

### PR DESCRIPTION
**Pull request by conao3**
Add GitHub Actions CI suite.

### CODE REVIEW

**Comment by conao3** [comment]
Full CI log is [here](https://github.com/conao3/ox-latex-subfigure/actions).

**Comment by linktohack** [comment]
Great! Thanks @conao3

**Review by linktohack — APPROVED** [review]
Perfect for me!

**Comment by conao3** [comment]
Thanks! merge this.

**Comment by conao3** [comment]
Please check this warning. https://github.com/linktohack/ox-latex-subfigure/actions
> GitHub Actions workflows can't be executed on this repository.
The billing plan for linktohack does not include access to GitHub Actions. Please contact the organization owner or billing manager for questions about the current billing plan.

hmm, I think GitHub Actions at OSS project is free. but...
I investigate this issue, but I have no idea about this.

**Pull request merged**
